import { defineVertical } from "../engine/schema";

/** Restaurants cited for rats, mice, roaches and flies, sold to pest control companies. */
export const vermin = defineVertical({
  id: "vermin",
  name: "Restaurant pest leads",
  audience: "pest control companies",
  noun: { singular: "pest citation", plural: "pest citations" },
  categories: {
    rats: { label: "Rats", weight: 35 },
    mice: { label: "Mice", weight: 30 },
    rodents: { label: "Rodents", weight: 30 },
    roaches: { label: "Roaches", weight: 30 },
    flies: { label: "Flies", weight: 15 },
    other: { label: "Other pests", weight: 15 },
    conditions: { label: "Pest-friendly conditions", weight: 8, optional: true },
  },
  flags: {
    pestControlOrdered: { label: "PEST CONTROL ORDERED", weight: 10 },
  },
  dedupeKey: "{id}:{date}",
  sources: {
    nyc: {
      type: "socrata",
      domain: "data.cityofnewyork.us",
      dataset: "43nn-pn8j",
      filter: {
        mode: "codes",
        field: "violation_code",
        codes: { "04K": "rats", "04L": "mice", "04M": "roaches", "04N": "flies", "08A": "conditions" },
      },
      fields: {
        id: ["camis"],
        name: ["dba"],
        address: ["building", "street", "boro"],
        zip: "zipcode",
        date: "inspection_date",
        phone: "phone",
        category: "cuisine_description",
        lat: "latitude",
        lng: "longitude",
        inspectionType: "inspection_type",
        notes: "violation_description",
        closed: { field: "action", containsAny: ["closed by", "re-closed"] },
        failed: { field: "score", gte: 28 },
      },
      requiredColumns: ["camis", "dba", "zipcode", "inspection_date", "violation_code", "action"],
      minWeeklyLeads: 20,
      rowLimit: 20000,
    },
    chicago: {
      type: "socrata",
      domain: "data.cityofchicago.org",
      dataset: "4ijn-s7e5",
      filter: {
        mode: "text",
        field: "violations",
        where: ["%INSECTS, RODENTS%"],
        items: [{ includes: "INSECTS, RODENTS" }],
        rules: [
          { category: "rats", pattern: "\\bRATS?\\b" },
          { category: "mice", pattern: "\\bMICE\\b|\\bMOUSE\\b" },
          { category: "rodents", pattern: "RODENT", unlessAny: ["rats", "mice"] },
          { category: "roaches", pattern: "ROACH" },
          { category: "flies", pattern: "\\bFLIES\\b|\\bFLY\\b|\\bGNATS?\\b" },
        ],
        fallbackCategory: "other",
        flags: [{ flag: "pestControlOrdered", pattern: "PEST CONTROL" }],
      },
      fields: {
        id: ["license_"],
        idFallback: "inspection_id",
        invalidIds: ["0"],
        name: ["aka_name", "dba_name"],
        address: ["address"],
        zip: "zip",
        date: "inspection_date",
        category: "facility_type",
        lat: "latitude",
        lng: "longitude",
        inspectionType: "inspection_type",
        failed: { field: "results", equals: "Fail" },
      },
      requiredColumns: ["license_", "dba_name", "zip", "inspection_date", "results", "violations"],
      minWeeklyLeads: 5,
      rowLimit: 5000,
    },
  },
  email: {
    subject: "{count} new {noun} in your area",
    intro: "Good morning, {company}. New {nouns} in {city}, hottest first:",
  },
  outreach: {
    seller: "a local pest control company",
    situation: "a restaurant (or other food business) that was recently cited for pests in a public health inspection",
    goal: "get a callback or a booked inspection before the business's re-inspection",
    offers: "speed (e.g. same-week service) and discretion (unmarked vehicle, after-hours visits)",
  },
});
