import type { Metadata } from "next";
import { LEGAL, LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Service · RatSignal" };

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>These terms govern your use of RatSignal, operated by {LEGAL.company}. By creating an account you agree to them on behalf of your business.</p>

      <h2>The service</h2>
      <p>RatSignal organizes public restaurant health inspection records into sales leads for pest control professionals. Data comes from city open-data sources and may be delayed, incomplete or contain errors made by the publishing agency. We don&apos;t guarantee that any lead needs service or will become a customer.</p>

      <h2>How you may use leads</h2>
      <ul>
        <li>Contact businesses honestly, without misrepresenting who you are or implying you work for a health department.</li>
        <li>Follow telemarketing, email and marketing laws, including the TCPA and CAN-SPAM. Don&apos;t send automated or prerecorded calls or texts to numbers from RatSignal.</li>
        <li>Don&apos;t resell, republish or share lead data outside your company.</li>
      </ul>

      <h2>Subscriptions</h2>
      <ul>
        <li>Plans start with a 7-day free trial. Unless you cancel before it ends, your subscription begins and renews monthly.</li>
        <li>Exclusive zip codes are billed per zip per month, prorated, and held only while your subscription is active. If it lapses, the zips are released.</li>
        <li>Cancel anytime in Settings; access continues until the end of the paid period. Fees are non-refundable except where required by law.</li>
      </ul>

      <h2>AI-drafted outreach</h2>
      <p>Call scripts, emails and letters are generated by AI as a starting point. Review and edit them before use; you&apos;re responsible for what you send.</p>

      <h2>Liability</h2>
      <p>The service is provided &quot;as is&quot;. To the extent the law allows, our total liability is limited to what you paid us in the 3 months before the claim.</p>

      <h2>Changes</h2>
      <p>We may update these terms and will notify customers by email of material changes.</p>

      <h2>Contact</h2>
      <p><a href={`mailto:${LEGAL.contact}`}>{LEGAL.contact}</a></p>
    </LegalPage>
  );
}
